;; Generated by find-file-in-project.
((nil . ((ffip-project-root . "/Users/barrie/.emacs.d/")
;;       (ffip-find-options . "-not -size +64k")
;;       (ffip-patterns . ("*.html" "*.js" "*.css" "*.java" "*.el" "*.js"))
;;       (ffip-prune-patterns . ("*/.git/*" "*/node_modules/*" "*/index.js"))
         )))